name: Hapus Workflow Lama

on:
  workflow_dispatch: # Memungkinkan Anda menjalankan ini secara manual tombol 'Run workflow'

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 0 # Ubah ke angka lain (misal: 7) jika ingin menyisakan log seminggu terakhir
          keep_minimum_runs: 0
