name: Update neko

on:
  schedule:
    - cron: ' */3 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  pet:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: Kyooyoukiee/YourTomo@main
        with:
          username: Kyooyoukiee
          timezone-offset-minutes: "420"
          pet-name: "niku"



